index:
    path: /
    controller: App\Controller\IndexController::index

campaign_new:
    path: /campaign/new
    controller: App\Controller\GameController::newCampaign

battle_new:
    path: /campaign/{campaignId}/battle/new
    controller: App\Controller\GameController::newBattle

battle_next_turn:
    path: /battle/{battleId}/nextTurn
    controller: App\Controller\BattleController::nextTurn

battle_attack:
    path: /battle/{battleId}/attack
    controller: App\Controller\BattleController::attack

battle_enemy_act:
    path: /battle/{battleId}/enemy/act
    controller: App\Controller\BattleController::enemyAct

stage_enemies:
    path: /stage/{stageId}/enemies
    controller: App\Controller\StageController::enemies